GET http://localhost:5000/api/posts/actives
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYyOTViYjJiZTZjOTY1MzYzZWRiY2M3YSJ9LCJpYXQiOjE2NTM5Nzk5NTksImV4cCI6MTY1NDA2NjM1OX0.kB_zSGGQXRLdWnQ2XV1fUlUIznWDgm2iMeS6dW_qyHM